CREATE OR REPLACE TABLE customer
(
    C_CUSTKEY       INT,
    C_NAME          VARCHAR,
    C_ADDRESS       VARCHAR,
    C_CITY          VARCHAR,
    C_NATION        VARCHAR,
    C_REGION        VARCHAR,
    C_PHONE         VARCHAR,
    C_MKTSEGMENT    VARCHAR
);

CREATE OR REPLACE TABLE lineorder
(
    LO_ORDERKEY             INT,
    LO_LINENUMBER           TINYINT,
    LO_CUSTKEY              INT,
    LO_PARTKEY              INT,
    LO_SUPPKEY              INT,
    LO_ORDERDATE            Date,
    LO_ORDERPRIORITY        VARCHAR,
    LO_SHIPPRIORITY         TINYINT,
    LO_QUANTITY             TINYINT,
    LO_EXTENDEDPRICE        INT,
    LO_ORDTOTALPRICE        INT,
    LO_DISCOUNT             TINYINT,
    LO_REVENUE              INT,
    LO_SUPPLYCOST           INT,
    LO_TAX                  TINYINT,
    LO_COMMITDATE           Date,
    LO_SHIPMODE             VARCHAR
);

CREATE OR REPLACE TABLE part
(
    P_PARTKEY       INT,
    P_NAME          VARCHAR,
    P_MFGR          VARCHAR,
    P_CATEGORY      VARCHAR,
    P_BRAND         VARCHAR,
    P_COLOR         VARCHAR,
    P_TYPE          VARCHAR,
    P_SIZE          TINYINT,
    P_CONTAINER     VARCHAR
);

CREATE OR REPLACE TABLE supplier
(
    S_SUPPKEY       INT,
    S_NAME          VARCHAR,
    S_ADDRESS       VARCHAR,
    S_CITY          VARCHAR,
    S_NATION        VARCHAR,
    S_REGION        VARCHAR,
    S_PHONE         VARCHAR
);

CREATE OR REPLACE TABLE date
(
    D_DATEKEY            Date,
    D_DATE               VARCHAR,
    D_DAYOFWEEK          VARCHAR,
    D_MONTH              VARCHAR,
    D_YEAR               SMALLINT,
    D_YEARMONTHNUM       INT,
    D_YEARMONTH          VARCHAR,
    D_DAYNUMINWEEK       TINYINT,
    D_DAYNUMINMONTH      TINYINT,
    D_DAYNUMINYEAR       SMALLINT,
    D_MONTHNUMINYEAR     TINYINT,
    D_WEEKNUMINYEAR      TINYINT,
    D_SELLINGSEASON      VARCHAR,
    D_LASTDAYINWEEKFL    TINYINT,
    D_LASTDAYINMONTHFL   TINYINT,
    D_HOLIDAYFL          TINYINT,
    D_WEEKDAYFL          TINYINT
);


COPY INTO lineorder(
    LO_ORDERKEY,
    LO_LINENUMBER,
    LO_CUSTKEY,
    LO_PARTKEY,
    LO_SUPPKEY,
    LO_ORDERDATE,
    LO_ORDERPRIORITY,
    LO_SHIPPRIORITY,
    LO_QUANTITY,
    LO_EXTENDEDPRICE,
    LO_ORDTOTALPRICE,
    LO_DISCOUNT,
    LO_REVENUE,
    LO_SUPPLYCOST,
    LO_TAX,
    LO_COMMITDATE,
    LO_SHIPMODE
) FROM 's3://bench-dataset/ssb/sf100/lineorder/' FILE_FORMAT =(TYPE = CSV, FIELD_DELIMITER = '|');
COPY INTO customer(C_CUSTKEY,C_NAME,C_ADDRESS,C_CITY,C_NATION,C_REGION,C_PHONE,C_MKTSEGMENT) FROM 's3://bench-dataset/ssb/sf100/customer/' FILE_FORMAT =(TYPE = CSV, FIELD_DELIMITER = '|');
COPY INTO date(
    D_DATEKEY,
    D_DATE,
    D_DAYOFWEEK,
    D_MONTH,
    D_YEAR,
    D_YEARMONTHNUM,
    D_YEARMONTH,
    D_DAYNUMINWEEK,
    D_DAYNUMINMONTH,
    D_DAYNUMINYEAR,
    D_MONTHNUMINYEAR,
    D_WEEKNUMINYEAR,
    D_SELLINGSEASON,
    D_LASTDAYINWEEKFL,
    D_LASTDAYINMONTHFL,
    D_HOLIDAYFL,
    D_WEEKDAYFL
) FROM 's3://bench-dataset/ssb/sf100/date/' FILE_FORMAT =(TYPE = CSV, FIELD_DELIMITER = '|');
COPY INTO supplier(
    S_SUPPKEY,
    S_NAME,
    S_ADDRESS,
    S_CITY,
    S_NATION,
    S_REGION,
    S_PHONE
) FROM 's3://bench-dataset/ssb/sf100/supplier/' FILE_FORMAT =(TYPE = CSV, FIELD_DELIMITER = '|');
COPY INTO part(
    P_PARTKEY,
    P_NAME,
    P_MFGR,
    P_CATEGORY,
    P_BRAND,
    P_COLOR,
    P_TYPE,
    P_SIZE,
    P_CONTAINER
) FROM 's3://bench-dataset/ssb/sf100/part/' FILE_FORMAT =(TYPE = CSV, FIELD_DELIMITER = '|');


CREATE OR REPLACE TABLE lineorder_flat
AS SELECT
     l.LO_ORDERKEY AS LO_ORDERKEY,
     l.LO_LINENUMBER AS LO_LINENUMBER,
     l.LO_CUSTKEY AS LO_CUSTKEY,
     l.LO_PARTKEY AS LO_PARTKEY,
     l.LO_SUPPKEY AS LO_SUPPKEY,
     l.LO_ORDERDATE AS LO_ORDERDATE,
     l.LO_ORDERPRIORITY AS LO_ORDERPRIORITY,
     l.LO_SHIPPRIORITY AS LO_SHIPPRIORITY,
     l.LO_QUANTITY AS LO_QUANTITY,
     l.LO_EXTENDEDPRICE AS LO_EXTENDEDPRICE,
     l.LO_ORDTOTALPRICE AS LO_ORDTOTALPRICE,
     l.LO_DISCOUNT AS LO_DISCOUNT,
     l.LO_REVENUE AS LO_REVENUE,
     l.LO_SUPPLYCOST AS LO_SUPPLYCOST,
     l.LO_TAX AS LO_TAX,
     l.LO_COMMITDATE AS LO_COMMITDATE,
     l.LO_SHIPMODE AS LO_SHIPMODE,
     c.C_NAME AS C_NAME,
     c.C_ADDRESS AS C_ADDRESS,
     c.C_CITY AS C_CITY,
     c.C_NATION AS C_NATION,
     c.C_REGION AS C_REGION,
     c.C_PHONE AS C_PHONE,
     c.C_MKTSEGMENT AS C_MKTSEGMENT,
     s.S_NAME AS S_NAME,
     s.S_ADDRESS AS S_ADDRESS,
     s.S_CITY AS S_CITY,
     s.S_NATION AS S_NATION,
     s.S_REGION AS S_REGION,
     s.S_PHONE AS S_PHONE,
     p.P_NAME AS P_NAME,
     p.P_MFGR AS P_MFGR,
     p.P_CATEGORY AS P_CATEGORY,
     p.P_BRAND AS P_BRAND,
     p.P_COLOR AS P_COLOR,
     p.P_TYPE AS P_TYPE,
     p.P_SIZE AS P_SIZE,
     p.P_CONTAINER AS P_CONTAINER
FROM lineorder AS l
        INNER JOIN customer AS c ON c.C_CUSTKEY = l.LO_CUSTKEY
        INNER JOIN supplier AS s ON s.S_SUPPKEY = l.LO_SUPPKEY
        INNER JOIN part AS p ON p.P_PARTKEY = l.LO_PARTKEY;